//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Il2CppDumper {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Il2CppDumper.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Il2CppDummyDll {
            get {
                object obj = ResourceManager.GetObject("Il2CppDummyDll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static string ProtocolExport_Start {
            get {
                return ResourceManager.GetString("ProtocolExport.Start", resourceCulture);
            }
        }
        
        internal static string Global_Success {
            get {
                return ResourceManager.GetString("Global.Success", resourceCulture);
            }
        }
        
        internal static string DummyAssemblyExporter_Start {
            get {
                return ResourceManager.GetString("DummyAssemblyExporter.Start", resourceCulture);
            }
        }
        
        internal static string Error_MetadataNotFound {
            get {
                return ResourceManager.GetString("Error.MetadataNotFound", resourceCulture);
            }
        }
        
        internal static string Global_Exit_RequireKey {
            get {
                return ResourceManager.GetString("Global.Exit.RequireKey", resourceCulture);
            }
        }
        
        internal static string Global_Usage {
            get {
                return ResourceManager.GetString("Global.Usage", resourceCulture);
            }
        }
        
        internal static string Global_Init_Metadata {
            get {
                return ResourceManager.GetString("Global.Init.Metadata", resourceCulture);
            }
        }
        
        internal static string Global_MetadataVersion {
            get {
                return ResourceManager.GetString("Global.MetadataVersion", resourceCulture);
            }
        }
        
        internal static string Global_Init_Il2cpp {
            get {
                return ResourceManager.GetString("Global.Init.Il2cpp", resourceCulture);
            }
        }
        
        internal static string Error_Il2cppNotSupport {
            get {
                return ResourceManager.GetString("Error.Il2cppNotSupport", resourceCulture);
            }
        }
        
        internal static string Global_Macho_SelectPlatform {
            get {
                return ResourceManager.GetString("Global.Macho.SelectPlatform", resourceCulture);
            }
        }
        
        internal static string Global_Il2cppVersion {
            get {
                return ResourceManager.GetString("Global.Il2cppVersion", resourceCulture);
            }
        }
        
        internal static string Global_Il2cpp_MayBeDumpWarning {
            get {
                return ResourceManager.GetString("Global.Il2cpp.MayBeDumpWarning", resourceCulture);
            }
        }
        
        internal static string Global_Il2cpp_RequireDumpAddress {
            get {
                return ResourceManager.GetString("Global.Il2cpp.RequireDumpAddress", resourceCulture);
            }
        }
        
        internal static string Error_UseManualMode {
            get {
                return ResourceManager.GetString("Error.UseManualMode", resourceCulture);
            }
        }
        
        internal static string Global_RequireCodeReg {
            get {
                return ResourceManager.GetString("Global.RequireCodeReg", resourceCulture);
            }
        }
        
        internal static string Global_RequireMetadataReg {
            get {
                return ResourceManager.GetString("Global.RequireMetadataReg", resourceCulture);
            }
        }
        
        internal static string Error_DefaultError {
            get {
                return ResourceManager.GetString("Error.DefaultError", resourceCulture);
            }
        }
        
        internal static string StructGenerator_Start {
            get {
                return ResourceManager.GetString("StructGenerator.Start", resourceCulture);
            }
        }
        
        internal static string Global_Dumping {
            get {
                return ResourceManager.GetString("Global.Dumping", resourceCulture);
            }
        }
        
        internal static string PE_CustomPELoader {
            get {
                return ResourceManager.GetString("PE.CustomPELoader", resourceCulture);
            }
        }
        
        internal static string Global_Searching {
            get {
                return ResourceManager.GetString("Global.Searching", resourceCulture);
            }
        }
        
        internal static string Error_ProtocolExporter_TargetAssemblyNotFound {
            get {
                return ResourceManager.GetString("Error.ProtocolExporter.TargetAssemblyNotFound", resourceCulture);
            }
        }
    }
}
